# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 12, 8, 4, 47, 36, 374085, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='customers.Customer'),
        ),
    ]
