# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20161208_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 9, 1, 34, 11, 926810, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 9, 1, 34, 22, 135058, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='package',
            name='SKU',
            field=models.IntegerField(),
        ),
    ]
