# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=255)),
                ('order_reference', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('ready_by', models.CharField(max_length=255)),
                ('packages', models.CharField(max_length=255)),
            ],
        ),
    ]
